### ISSUE TITLE
Missing feature: show the spec of a MIG profile

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/mig-parted#1]
It would be nice if we could the tool to query content of a configuration file (most important is the 2nd command):

```
# nvidia-mig-parted show -f examples/config.yaml
version: v1
mig-configs:
  - all-disabled
  - all-enabled
  -  ...

# nvidia-mig-parted show -f examples/config.yaml -c all-balanced
version: v1
all-balanced:
  - devices: all
    mig-enabled: true
    mig-devices:
      "1g.5gb": 2
      "2g.10gb": 1
      "3g.20gb": 1
```

along with `nvidia-mig-parted export`, this would allow a script to detect if applying a profile would change the state of `mig-enabled` property
