### ISSUE TITLE
Information about a partition type

### ISSUE THREAD

**Issue by bharathappali** [NVIDIA/mig-parted#100]
I have a NVIDIA A100 40GB variant and I would like to know if this particular config works, before I try out to apply on the node

```
custom-mig-config:
        - devices: [0,3,4,5,6,7]
          mig-enabled: false
        - devices: [1,2]
          mig-enabled: true
          mig-devices:
            "4g.20gb": 1
            "3g.20gb": 1
```

I'm facing `custom-mig-config` not found error when I'm trying to apply it. Just wanted to confirm if it's the issue with the config or some other operational or procedural mistake I have done. 

Thanks in advance!
