### ISSUE TITLE
Add mig config watch then reload config file

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/mig-parted#108]
https://github.com/NVIDIA/gpu-operator/issues/891

About this issue, I want to add some logic to watch for changes in the `/mig-parted-config/config.yaml` file and trigger a reload of the configuration file.

**Comment by lengrongfu** [comment]
eg:
`custom-config` before config value is: 
```
version: v1
mig-configs:
 custom-config:
    - devices: all
       mig-enabled: true
       mig-devices:
         3g.40gb: 2
```

`custom-config` after config value is: 
```
version: v1
mig-configs:
 custom-config:
    - devices: all
       mig-enabled: true
       mig-devices:
         1g.10gb: 3
         2g.20gb: 2
```
