### ISSUE TITLE
"7g.40gb" configuration missing in examples/config.yaml

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/mig-parted#2]
I think this config is missing in `examples/config.yaml`, to be exhaustive with the list of configurations compatible with the `single` strategy

```
      all-7g.40gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.40gb": 1
```
